### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by eklundchristopher** [w0lfschild/NoFavicons#1]
_First of all, allow me to thank you. I was expecting Chrome 51 to be the last of my NoFavicon days (using the version provided by Michael Phines), but alas, here you and your wonderful repositories are. Thank you!_

To the issue at hand, every once in a while, the odd bookmark will resize as if it added an invisible favicon (but to the right of the text rather than to the left). I have yet to find a consistent reason for this, but what I know is, it happens on clicking said bookmark. It doesn't seem to matter how long Chrome has been running for.

<img width="328" alt="screen shot 2016-08-04 at 05 07 27" src="https://cloud.githubusercontent.com/assets/933531/17389162/fa16687a-5a01-11e6-9449-970e5b99379f.png">

I'm running the latest version of mySIMBL and NoFavicons on OSX 10.11.2. Any help or time you can spend on this would be much appreciated. Albeit not a breaking issue, it would be nice in order to please my OCD ;-)

**Comment by w0lfschild** [comment]
Yeah this is something I've encountered myself where sometimes when launching chrome a few bookmarks end up having a blank icon space on the left side.

I think it has something to do with the bookmark item trying to update it's image.

I'll look into this at some point but for now opening a new window will have fixed bookmarks.

**Comment by eklundchristopher** [comment]
Sure thing, just thought I'd bring it to your attention. Thanks!

**Comment by w0lfschild** [comment]
I've made it so the tweak fixes this without opening a new tab. Still shows up sometimes when opening chrome but should fix itself within a second or two.

**Comment by eklundchristopher** [comment]
Hi again.

It seems after updating Chrome to version 60 _(60.0.3112.78 on Sierra 10.12.5)_, the spacing is back, however, this time, it seems to be permanent rather than temporary (and across the board).

I've tried uninstalling & re-installing the plugin to no avail.

Thanks again for a great plugin.

**Comment by w0lfschild** [comment]
Yeah this was annoying the crap out of me so I spent a good chunk of time today and created a solution for Chrome 60+

It has an issue where dragging bookmark buttons around won't show the changes until you open a new window or restart Chrome. Since I don't do that much it's not necessarily something that will get fixed soon or maybe even ever.

The plus side is this seems to be totally consistent and since the spacing is done all manually that allows for things like the ability to edit the code to adjust spacing or make the buttons right aligned or centered.

I'll push out the new build to mySIMBL soon.

<img width="1113" alt="screen shot 2017-08-03 at 12 11 51 am" src="https://user-images.githubusercontent.com/1920148/28910156-6df58684-77e0-11e7-860d-82892ce21e4b.png">

**Comment by eklundchristopher** [comment]
You're a god among men, my friend.

I don't really move bookmarks around either, so not an issue on my behalf. Thanks for your great work!

**Comment by eklundchristopher** [comment]
The thorn in your shoe is back, I'm afraid.

Whenever the browser window is downsized and then resized back up, the bookmarks get sent across to the bar to weird positions, get spaced out or cut off.

As per usual, there's no rush and I appreciate the help/effort you've already put into this.

PS. I've noticed it happens more frequently when downsizing the browser and then resizing it using a window manager app such as Magnet.

Cheers.

**Comment by w0lfschild** [comment]
Luckily as an exclusive Chrome user myself I try to keep this updated. With that said here comes 1.8 which will hopefully be the last one I need to do for a while 🤞.

Haven't tested on older macOS or Chrome yet so hopefully that's working.

This version fixes a slew of issues. The only problem left that I can think of is that the bookmarks get added to the overflow button when there is still space left in the bar, I'm not sure I'll be able to fix that one.

1.8 Changelog:
- Fix oversized overflow bookmarks button
- Fix issues caused when Apps Shortcut button was toggled
- Fix buttons not moving when dragged to new position
- Fix button display issues when window was resized
- Fix issue where removing a bookmark would leave an (empty) button that crashed the browser if clicked

Should be live on mySIMBL now.

**Comment by eklundchristopher** [comment]
Thank you, much appreciated as per usual!
